language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vikramvdeshpande/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true vikramvdeshpande/docker-react npm run test -- --coverage